### ISSUE TITLE
Bad kpm-0.6.0 package

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-cloud#114]
Multiple kpm gems are packaged in the self-contained `.tar.gz` (and none are the right version).

Unclear if it's an environment issue (e.g. build tree not clean when the package was generated) or if there is an actual bug in the build process, but we should at least make sure this doesn't happen (e.g. fix build script to always cleanup first).

```
$ docker run -ti killbill/base:0.19.x /bin/bash
tomcat@3851f5742757:~$ kpm system | grep KPM
|      KPM |     0.5.3 |
tomcat@3851f5742757:~$ which kpm
/opt/kpm-0.6.0-linux-x86_64/kpm
tomcat@3851f5742757:~$ find /opt/kpm-0.6.0-linux-x86_64/ -name version.rb | grep lib/kpm
/opt/kpm-0.6.0-linux-x86_64/lib/vendor/ruby/2.2.0/gems/kpm-0.5.3/lib/kpm/version.rb
/opt/kpm-0.6.0-linux-x86_64/lib/vendor/ruby/2.2.0/gems/kpm-0.5.1/lib/kpm/version.rb
/opt/kpm-0.6.0-linux-x86_64/lib/vendor/ruby/2.2.0/gems/kpm-0.5.2/lib/kpm/version.rb
```

**Comment by sachgits** [comment]
have tried to run killbill and kaui on GCP kubernetes but it does'nt work but killbill wasn't working despite the fact that it used to work locally with docker killbill:0.18  2 months ago could these be the reason why

**Comment by pierre** [comment]
@sachgits Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) for support questions. See also https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md.

**Comment by pierre** [comment]
Couple of issues following https://github.com/killbill/killbill-cloud/issues/114:

* In the [packaged tarball](https://search.maven.org/#search%7Cga%7C1%7Ckpm), the `VERSION` string isn't expanded under `lib/vendor/Gemfile`, causing `kpm` to throw `There was an error in your Gemfile, and Bundler cannot continue.`
* There is a new warning regarding `json` extensions, causing the ansible module `killbill_facts` to fail:
```
kpm-0.6.1-osx > ./lib/ruby/bin/ruby /path/to/killbill-cloud/ansible/library/killbill_facts kpm.yml
Ignoring json-1.8.6 because its extensions are not built.  Try: gem pristine json --version 1.8.6
/path/to/kpm-0.6.1-osx/lib/ruby/lib/ruby/2.2.0/json/common.rb:155:in `initialize': no implicit conversion of nil into String (TypeError)
	from /path/to/kpm-0.6.1-osx/lib/ruby/lib/ruby/2.2.0/json/common.rb:155:in `new'
	from /path/to/kpm-0.6.1-osx/lib/ruby/lib/ruby/2.2.0/json/common.rb:155:in `parse'
	from /path/to/killbill-cloud/ansible/library/killbill_facts:13:in `with_captured_stdout'
	from /path/to/killbill-cloud/ansible/library/killbill_facts:30:in `<main>'
```
 1. I'm unclear if we can safely build and package the native extensions cross-platform in the packages. If we cannot, we should ensure only the `pure` version is loaded (to make the warning disappear).
 2. We should fix this [TODO](https://github.com/killbill/killbill-cloud/blob/387c0995d9865a0177195adf983acda8c64dcd2f/ansible/library/killbill_facts#L7), i.e. use the newly available json output in the ansible library to avoid having to parse STDOUT
