### ISSUE TITLE
KAUI "latest" docker image depends on tomcat7 user

### ISSUE THREAD

**Issue by indranil32** [killbill/killbill-cloud#133]
If I try to run -> docker-compose -f docker-compose.kb.yml -p kb up  
[https://github.com/killbill/killbill-cloud/blob/master/docker/compose/docker-compose.kb.yml]
It gives me error saying "user: tomcat7 not found"

Please point "latest" to 1.0.5 or update the compose file to :- 
kaui:
    image: killbill/kaui:1.0.5

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
