### ISSUE TITLE
failed to start docker image on mac with default memory limit 2GB

### ISSUE THREAD

**Issue by v1ct0r** [killbill/killbill-cloud#134]
If start killbill stack 
`docker-compose -f docker-compose.kb.yml -p kb up`
with Mac Docker CE (https://docs.docker.com/docker-for-mac/install/) default settings, the stack didn't start properly because docker for mac limits memory to 2GB but killbill container required more than 2GB to start
After increasing memory available to docker to 4GB the stack starts properly
Please mention the memory requirements in Quick Start section
https://github.com/killbill/killbill-cloud/tree/master/docker/compose#quick-start

**Comment by pierre** [comment]
Could you submit a PR?

**Comment by v1ct0r** [comment]
https://github.com/killbill/killbill-cloud/pull/135
