### ISSUE TITLE
Error when running "make": Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

### ISSUE THREAD

**Issue by stevennt** [killbill/killbill-cloud#136]
While running "make" I have the below errors. Anyone having similar issue? Thanks.

Starting elk_kibana_1 ... 
Starting elk_logstash_1 ... 
Starting elk_kibana_1   ... error
elk_curator_1 is up-to-date

ERROR: for elk_kibana_1  Cannot start service kibana: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/root/Workspace/docker/abnpay/killbill-cloud/docker/compose/kibana/config/kibana.yml\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/overlay2/d3ba845d2d059b564fa179df2a7bec0721bf0050b748b9150564c22a96fe1eed/merged\\\" at \\\"/mnt/sda1/var/lib/docker/overlay2/d3ba845d2d059b564fa179df2a7bec0721bf0050b748b9150564c22a96fe1eed/merged/usr/share/kibana/config/kibaStarting elk_logstash_1 ... error

ERROR: for elk_logstash_1  Cannot start service logstash: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/root/Workspace/docker/abnpay/killbill-cloud/docker/compose/logstash/config/logstash.yml\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/overlay2/8a1e10d5a381c10af614f748b12f43a41349994f1db653d2dcc09e2336eabe4d/merged\\\" at \\\"/mnt/sda1/var/lib/docker/overlay2/8a1e10d5a381c10af614f748b12f43a41349994f1db653d2dcc09e2336eabe4d/merged/usr/share/logstash/config/logstash.yml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for kibana  Cannot start service kibana: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/root/Workspace/docker/abnpay/killbill-cloud/docker/compose/kibana/config/kibana.yml\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/overlay2/d3ba845d2d059b564fa179df2a7bec0721bf0050b748b9150564c22a96fe1eed/merged\\\" at \\\"/mnt/sda1/var/lib/docker/overlay2/d3ba845d2d059b564fa179df2a7bec0721bf0050b748b9150564c22a96fe1eed/merged/usr/share/kibana/config/kibana.yml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for logstash  Cannot start service logstash: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/root/Workspace/docker/abnpay/killbill-cloud/docker/compose/logstash/config/logstash.yml\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/overlay2/8a1e10d5a381c10af614f748b12f43a41349994f1db653d2dcc09e2336eabe4d/merged\\\" at \\\"/mnt/sda1/var/lib/docker/overlay2/8a1e10d5a381c10af614f748b12f43a41349994f1db653d2dcc09e2336eabe4d/merged/usr/share/logstash/config/logstash.yml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
Makefile:18: recipe for target 'elk' failed
make: *** [elk] Error 1

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
