### ISSUE TITLE
Docker: Exit on tomcat error

### ISSUE THREAD

**Issue by mrmstn** [killbill/killbill-cloud#137]
Whenever tomcat crashes (in case there's not enough ram for example), the container does not exit since the attached process is the tail process for the logs. 

This behaviour breaks also some common workflows like `--restart on-failure` and results in a "connection refused" when somebody tries to connect to killbill, but from the "container" perspective the container looks fine.

**Comment by pierre** [comment]
Hi @mrmstn,

Thanks for the report!

I have a proposed solution in https://github.com/killbill/killbill-cloud/pull/139. Would you be able to verify it?
