### ISSUE TITLE
jdbc with sql

### ISSUE THREAD

**Issue by TmyWu** [killbill/killbill-cloud#197]
Hello,

I'm currently having an issue connecting killbill and kaui to a RDS databse, with use of SSL
I'm using the docker-compose file and filling in the 'KILLBILL_DAO_URL' and 'KAUI_CONFIG_DAO_URL' with:
jdbc:mysql://RDS-DNS:3306/killbill?sslMode=PREFERRED and jdbc:mysql://RDS-DNS:3306/killbill?sslMode=PREFERRED&trustCertificateKeyStoreUrl=global-bundle.pem
accordingly with https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-jdbc-url-format.html#connector-j-url-properties

When I use the '&' to add more 'variables' it gets stuck in the ansible part. I tried encoding it, when I do that I see in debug that it doesn't really recognize what is going on.

I hereby ask for help on how I should go about connecting to RDS database while using SSL. 
I thank you in advance for your patience and understanding.

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead and share your `docker-compose.yml` file, as well as the Kill Bill logs. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
