### ISSUE TITLE
Sentry Support for Docker

### ISSUE THREAD

**Issue by mubeta06** [killbill/killbill-cloud#215]
The instructions for enabling Sentry instrumentation (https://docs.killbill.io/latest/errors-sentry.html#_set_up_sentry) make mention of editing the following two lines of `/var/lib/tomcat/bin/setenv2.sh`

- -Dcom.killbill.sentry.enable=false
- -Dcom.killbill.sentry.dsn=

however the said file with the official docker image has no such line permitting the configuration of Sentry.

**Comment by pierre** [comment]
Sentry is currently only supported on our AWS AMIs.

In the future, please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
