### ISSUE TITLE
Killbill unable to connect to Postgres server 

### ISSUE THREAD

**Issue by HanumanthaRAON** [killbill/killbill-cloud#249]
Hi Team,

We are trying to upgrade Killbill server to latest  but getting below error while running advanced search in Kaui page. can someone please check and hep us to resolve the issue 

![image](https://github.com/killbill/killbill-cloud/assets/20111534/3e6b6905-493e-4811-b547-e81456e0d69b)

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
