### ISSUE TITLE
Add support for DDL files in KPM

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-cloud#3]
It would be nice if KPM could install the DDL files too. We probably need to add a flag, so upgrades don't clobber existing tables.

**Comment by sbrossie** [comment]
Yeah it would be nice ;-)

**Comment by pierre** [comment]
Some thoughts:

* Because Ruby plugins already rely on ActiveRecord (see [here](https://github.com/killbill/killbill-cybersource-plugin/blob/master/db/schema.rb) for example), we should use Rails migrations for these
* We don't have a migration solution today for Java code (Kill Bill or Java plugins). We could investigate https://flywaydb.org/, and if it's a fit, use it for both

KPM could then have a new verb to detect outdated DB schemata (and maybe run it by default post installation too) and output the SQL to run the migration(s) (`ALTER` statements and updates to migration versioning tables). This would be more useful in practice than simply having `kpm` run all migrations because:

1. In production, only DBAs with special access can effectively change tables structure
2. We don't want to force the DBA to use special tools (maven, ruby, ...) to apply the changes

**Comment by sbrossie** [comment]
I agree with the thoughts: 
1. I think we want to provide the best tooling so the manual install/update becomes easy
2. We don't want any automatic magic

**Comment by pierre** [comment]
Proposal: https://github.com/killbill/killbill-cloud/commit/18f069efc499313c9f60c3ac39f39ef30002eaad.

**Comment by pierre** [comment]
@bgandon, @beccagaspard: we've published a proposal on how database migrations would work with Kill Bill and its plugins: https://github.com/killbill/killbill-docs/blob/v3/userguide/tutorials/database_migrations.adoc.

Since you both expressed interest in such tooling, feel free to let us know if you have any feedback and/or if this would work in your organizations. Thanks!
