### ISSUE TITLE
jruby.jar story

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-cloud#30]
Somehow KPM should detect whether `jruby.jar ` is correctly installed and with correct version.

**Comment by pierre** [comment]
Wouldn't it be easier to do it in `DefaultKillbillNodesService` instead? Kill Bill already knows the platform version and the `jruby.jar` has the platform version under `META-INF/maven/org.kill-bill.billing/killbill-platform-osgi-bundles-jruby/pom.properties`.

Work is required though to expose an API from platform to get the `jruby.jar` [path](https://github.com/killbill/killbill-platform/blob/master/osgi/src/main/java/org/killbill/billing/osgi/FileInstall.java#L244-L252).

**Comment by sbrossie** [comment]
After some discussions:
1. When Kill Bill starts, it warns if there is no `jruby.jar` (already in place), and if it exists, it checks the correct version as described above and also warns if this is not the right version
2. On KPM side:
  * During `install` we should end up with correct jruby.jar version (that is install it if missing or clobber it with new one if wrong version)
  * During `pull` of a jruby plugin at least warn if there is no `jruby.jar` and print instructions on how to add it.

**Comment by sbrossie** [comment]
Changes in Kill Bill have been made:
* [platform diff](https://github.com/killbill/killbill-platform/commit/e9aace4800edf4354d7b692662c9ddfc6d6ae05a)
* [killbill diff](https://github.com/killbill/killbill/commit/d413b0a36c27ce24597133f6c2d9fdbb999995a6)
