### ISSUE TITLE
db.expose error

### ISSUE THREAD

**Issue by benbro** [killbill/killbill-cloud#42]
```
ERROR: Validation failed in file 'killbill-cloud/docker/compose/docker-compose.kb.yml', reason(s):
db.expose is invalid: should be of the format 'PORT[/PROTOCOL]
```
Maybe it should be?
```
expose:
    - "3306"
```

**Comment by sbrossie** [comment]
@benbro It looks like docker keeps the changing the format of the file. Which version are you using?

**Comment by benbro** [comment]
https://github.com/docker/compose/releases/tag/1.6.2

I've run "make run-kb " and installed the DLL.
Am I supposed to be able to login as bob/lazar at http://localhost:9090?

**Comment by sbrossie** [comment]
@benbro It looks like format has changed. We will take a look and fix it. Thanks for reporting the issue.

**Comment by benbro** [comment]
There is a pending PR
https://github.com/killbill/killbill-cloud/pull/36
