### ISSUE TITLE
KillBillClient.api_key, KillBillClient.api_secret have not been set

### ISSUE THREAD

**Issue by benbro** [killbill/killbill-cloud#43]
I followed the compose README.
When logging in at the first time with admin/password I'm getting the following error:
```
Error while retrieving tenants: No tenants configured for users AND KillBillClient.api_key, KillBillClient.api_secret have not been set
```
Isn't it what KAUI_API_KEY and KAUI_API_SECRET are for?
https://github.com/killbill/killbill-cloud/blob/master/docker/compose/docker-compose.kb.yml#L24

**Comment by sbrossie** [comment]
@benbro Please use the [mailing list](https://groups.google.com/forum/#!forum/killbilling-users) for questions (github issues is not the right place for that).
