### ISSUE TITLE
Include the DDLs in the docker image and install on first run

### ISSUE THREAD

**Issue by benbro** [killbill/killbill-cloud#45]
The README says to install the DDL after make run-kb.
Is there a reason not to include the DDLs in the image instead of downloading them from github?
The killbill container can install the DDLs from the local files on first run. It knows the DB user and password.
CREATE database IF NOT EXISTS killbill; CREATE database IF NOT EXISTS kaui;
The next two commands should only run on the first time so we don't reset the database.

The DDL version in the README should be 0.16 instead of 0.15 or point to /latest/ that will always be up to date.
http://docs.killbill.io/0.15/ddl.sql
https://github.com/killbill/killbill-cloud/blob/master/docker/compose/README.md

**Comment by pierre** [comment]
This is now provided by the `killbill/mariadb` image. See http://killbill.io/blog/having-fun-with-docker-stripe-and-kill-bill-v2/.
