### ISSUE TITLE
docker-compose commands in the readme need to point the yml file

### ISSUE THREAD

**Issue by benbro** [killbill/killbill-cloud#50]
The docker-compose README show several commands to manage the kb project.
A file named docker-compose.yml is expected.

```
ERROR: 
        Can't find a suitable configuration file in this directory or any parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml, fig.yml, fig.yaml
```

We need to add '-f  docker-compose.kb.yml':
```
cd killbill-cloud/docker/compose
docker-compose -p kb -f docker-compose.kb.yml ps
docker-compose -p kb -f docker-compose.kb.yml restart killbill
docker-compose -p kb -f docker-compose.kb.yml restart kaui
```

I tried to restart killbill with the correct command. It stopped the container but didn't start again.
```
sudo do-compose -p kb -f docker-compose.kb.yml restart killbill
```
I'm using latest killbill on ubuntu 16.04 with stable docker and docker-compose packages.

**Comment by pierre** [comment]
> We need to add '-f docker-compose.kb.yml'

👍 Could you submit a PR?

> with stable docker and docker-compose packages.

Which versions exactly?

Looks like Xenial ships with [docker-compose 1.5.2](https://launchpad.net/ubuntu/xenial/+source/docker-compose) but the latest version is [1.7.0](https://github.com/docker/compose/releases).

Did you follow https://docs.docker.com/engine/installation/linux/ubuntulinux/ to pull from apt.dockerproject.org?

**Comment by benbro** [comment]
I'll submit a PR for the readme.

I've tried latest docker and docker-compose on ubuntu 14.04 and restart doesn't work there either.

**Comment by pierre** [comment]
> I'll submit a PR for the readme.

Thanks!

> I've tried latest docker and docker-compose on ubuntu 14.04 and restart doesn't work there either.

That sounds more like an issue with docker-compose itself: if you can reproduce it on 1.7.0, I would contact https://forums.docker.com/.

**Comment by benbro** [comment]
Unless the killbill container gets stuck when stopping it and required a forced shutdown.

**Comment by pierre** [comment]
> Unless the killbill container gets stuck when stopping it and requires a forced shutdown.

But even so, wouldn't compose start it automatically after the forced shutdown?
