### ISSUE TITLE
Can we revisit the static file : plugins_directory.yml

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-cloud#6]
Today our docker images rely on a static file plugins_directory.yml to extract the versions of the plugin:
- That means all plugins need to exist in that file
- Also all versions must be up-to-date

Could we instead pass the version instead of a flag `-e KILLBILL_PLUGIN_STRIPE=1` and extract dynamically from maven?

**Comment by sbrossie** [comment]
The other issue is that we need different versions of plugins depending on the KB version we are using (0.14.x, 0.15.x,...)

**Comment by pierre** [comment]
We've discussed it in the past: we need a centralized location for this metadata and this file seems to be the easiest way to do it.
Changing it at this point is also a large effort (e.g. KPM plugin would need to be updated).
