### ISSUE TITLE
Docker Compose Conflict

### ISSUE THREAD

**Issue by markrey** [killbill/killbill-cloud#60]
Following the instructions of :
https://github.com/killbill/killbill-cloud/tree/master/docker/compose#kill-bill

`make run-kb` Will download DOCKER LATEST TAG ( 0.17 )

and instructions below that will have 0.16 version of database. That creates the DB fields mismatch error. 

```
host> docker exec -ti kb_killbill_1 /bin/bash
tomcat7@container:/var/lib/tomcat7$ mysql -h db -uroot -pkillbill -e 'create database killbill; create database kaui'
tomcat7@container:/var/lib/tomcat7$ curl -s http://docs.killbill.io/0.16/ddl.sql | mysql -h db -uroot -pkillbill killbill
tomcat7@container:/var/lib/tomcat7$ curl -s https://raw.githubusercontent.com/killbill/killbill-admin-ui/master/db/ddl.sql | mysql -h db -uroot -pkillbill kaui

```

To fix it i just updated the make run-kb file to 0.16.9 image.

**Comment by sbrossie** [comment]
ack we need to update our script to point to the right thing..

**Comment by markrey** [comment]
Feel free to close once done.

**Comment by skuda** [comment]
I just did a pull request to get the correct, at the time of writing, DDL version.
PR https://github.com/killbill/killbill-cloud/pull/82
