### ISSUE TITLE
KPM: Extracting plugin_name from jarfile is fragile

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-cloud#61]
See [code](https://github.com/killbill/killbill-cloud/blob/master/kpm/lib/kpm/base_installer.rb#L158)

**Comment by sbrossie** [comment]
This is really annoying and should be fixed: Example:

```
kpm install_java_plugin 'dev:xxx-foo' --from-source-file="/Somewhere/xxx-foo/target/xxx-foo-1.0.0.jar" --version="1.0.0" --destination=/var/tmp/mybundles
```

As a result the entry `/var/tmp/mybundles/plugins/java/xxx` will be created (and if multiple plugins starts with `xxx`, then each install overrides previous one.

**Comment by sbrossie** [comment]
@wwjbatista Re-opening the task. I think you fix 'almost' works, but not for all cases:

```
> file_path="/Somewhere/xxx-foo/target/xxx-foo-1.0.0.jar"
"xxx-foo"  => GOOD

> file_path="/Somewhere/xxx-foo/target/xxx-foo-1.0.0-SNAPSHOT.jar" 
"xxx-foo--SNAPSHOT"   => NO
```

The generic issue is that we could have random artifact name such as `xxx-foo-1.2.3.263541263412.jar` or whatever else.  

1. I think we should at support the default `SNAPSHOT` (very standard)
2. As a default, if name does not math regex, have a sane default. Maybe stop at the last `-` ?

@pierre Any thoughts?

**Comment by pierre** [comment]
Interesting that the `SNAPSHOT` one doesn't work, we have a test specifically for this: https://github.com/killbill/killbill-cloud/commit/576e3ff92e2934ddc1a3c096647f742a73243271#diff-def9654044137b79bf1d315ac4671d1bR62.

**Comment by sbrossie** [comment]
Also, something that i noticed is that we need to specify the version (but we should not have to, as it can be extracted):
```
kpm install_java_plugin analytics --from-source-file=/SOMETHING/killbill/killbill-analytics-plugin/target/analytics-plugin-4.2.4-SNAPSHOT.jar 
no implicit conversion of nil into String
/Users/sbrossier/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/pathname.rb:389:in `initialize'
/Users/sbrossier/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/pathname.rb:389:in `new'
/Users/sbrossier/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/pathname.rb:389:in `join'
```

However, following works:

```
kpm install_java_plugin analytics --from-source-file=/Users/sbrossier/Src/killbill/killbill-analytics-plugin/target/analytics-plugin-4.2.4-SNAPSHOT.jar --version=4.2.4-SNAPSHOT
I, [2017-08-07T14:33:14.130954 #3374]  INFO -- : Successful installation of ...
```
