### ISSUE TITLE
Kibana plugin fails in Compose scripts

### ISSUE THREAD

**Issue by jcboysha** [killbill/killbill-cloud#75]
Got an error trying to make in the compose directory: 

Service 'kibana' failed to build: The command '/bin/sh -c kibana plugin --install elastic/sense' returned a non-zero code: 64

Anyone have this issue? If you have, do you have any ideas on a solution?

**Comment by jcboysha** [comment]
fixed this by performing the following:

kibana/Dockerfile:
- Modify line 1 from FROM kibana:latest to FROM kibana:4.6.4
- Modify line 3 from RUN apt-get update && apt-get install -y netcat to RUN apt-get update

Manually installed nmap-ncat and aliased netcat->ncat

There is now an issue with elk that I am debugging.

**Comment by sbrossie** [comment]
@jcboysha Freezing the kibana version is probably a good idea (for ensuring stability). However i am confused with the part that removes `apt-get install -y netcat`. Do you have more details on what fails?

**Comment by jcboysha** [comment]
Netcat is, apparently, deprecated? It's replaced by nmap-ncat, which does the same job. 

Currently, the issue I'm having is Makefile:30 build docker compose failed

**Comment by jcboysha** [comment]
Looks like a problem with ruby.

**Comment by jcboysha** [comment]
Now I'm getting a timeout for influxdb, so I think I'm past the problem.
