### ISSUE TITLE
no LATEST tag for killbill/mariadb on dockerhub

### ISSUE THREAD

**Issue by nickolasclarke** [killbill/killbill-cloud#77]
when trying to use the the [docker guide](http://killbill.io/blog/having-fun-with-docker-stripe-and-kill-bill-v2/) and modifying the `docker-compose.yml` file to use the latest image, it fails when trying to pull the manifest for `killbill/mariaDB` because there is no `latest` tag designated in the hub.

**Comment by pierre** [comment]
We don't publish `latest` images for MariaDB, as it would be hard to track which DDL version is installed.

That being said, I've just pushed `killbill/mariadb:0.18` for Kill Bill 0.18.x.

**Comment by pierre** [comment]
See also https://groups.google.com/forum/#!topic/killbilling-users/30PhYG6-z9U.
